export const JOB_EVENTS = {
  JOB_CREATED: "JOB_CREATED",
  JOB_STARTED: "JOB_STARTED",
  JOB_COMPLETED: "JOB_COMPLETED",
  JOB_FAILED: "JOB_FAILED",
  JOB_RETRY_SCHEDULED: "JOB_RETRY_SCHEDULED",
  JOB_DLQ: "JOB_DLQ",
  JOB_RECOVERED: "JOB_RECOVERED",
  WORKER_DEAD: "WORKER_DEAD",
};
