#!/bin/bash
source "$(dirname "$0")/utils.sh"

echo -e "${YELLOW}=== 4. Leader Failover Mode ===${NC}"
echo "Purpose: Does leader election actually work?"

export LAB_WORKERS=1
export LAB_SCHEDULERS=3
start_cluster

echo "Wait for schedulers to elect a leader..."
sleep 5

# Identify the leader from Redis
LEADER_ID=$(docker exec distributed-task-platform-redis-1 redis-cli get "scheduler:leader")
echo "Current Leader is: $LEADER_ID"

if [ -z "$LEADER_ID" ]; then
    echo -e "${RED}No leader found!${NC}"
    exit 1
fi

# The container name format is typically distributed-task-platform-scheduler-service-N
# Wait, LEADER_ID is the UUID generated by the scheduler service, not the container name.
# To kill the leader, we can just kill one of the schedulers and verify leadership changes.
echo "Killing scheduler-service-1 (whether it's leader or not, it will force a re-election if it was)"
docker stop distributed-task-platform-scheduler-service-1

echo "Waiting for TTL expiration and new election (20s)..."
sleep 20

NEW_LEADER_ID=$(docker exec distributed-task-platform-redis-1 redis-cli get "scheduler:leader")
echo "New Leader is: $NEW_LEADER_ID"

if [ "$LEADER_ID" != "$NEW_LEADER_ID" ] && [ -n "$NEW_LEADER_ID" ]; then
    echo -e "${GREEN}Leader successfully failed over!${NC}"
else
    if [ "$LEADER_ID" == "$NEW_LEADER_ID" ]; then
        echo -e "${YELLOW}Scheduler 1 was not the leader, so leader didn't change (still $NEW_LEADER_ID).${NC}"
        echo -e "${GREEN}System remained stable.${NC}"
    else
        echo -e "${RED}Failover failed! No new leader elected.${NC}"
    fi
fi

# Bring it back up
docker start distributed-task-platform-scheduler-service-1
